# Generated by Django 5.1.6 on 2025-02-26 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
    ]
