# Generated by Django 5.1.6 on 2025-03-06 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_aboutus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
