# Generated by Django 5.1.6 on 2025-03-06 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_content_post_is_published_post_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
