# Generated by Django 5.1.6 on 2025-03-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_rename_content_post_about_post_ingredients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img_url',
        ),
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
    ]
